name: zulfaniz_store
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

# --------------------- PACKAGES ----------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  lottie: ^3.1.2
  url_launcher: ^6.1.12
  connectivity_plus: ^5.0.1
  carousel_slider: ^4.2.1
  flutter_native_splash: ^2.3.2
  smooth_page_indicator: ^1.1.0

  # Icons
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1


  # Product Specific
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1

  #firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.13.1

# --------------------- END PACKAGES ----------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  # --------------------- LOCAL ASSETS ----------------------#
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/users/

  fonts:
    - family: Poppins