name: zulfaniz_store
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

# --------------------- PACKAGES ----------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  carousel_slider: ^4.2.1
  flutter_native_splash: ^2.3.2
  smooth_page_indicator: ^1.1.0

  # Icons
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1


  # Product Specific
  readmore: ^3.0.0


# --------------------- END PACKAGES ----------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  # --------------------- LOCAL ASSETS ----------------------#
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/users/

  fonts:
    - family: Poppins